### ISSUE TITLE
project does not compile : Cannot find source file: lcd.c

### ISSUE THREAD

**Issue by DNL2023** [temcocontrols/T3-programmable-controller-on-ESP32#1]
Hi! , 

i followed the instructions step - by - step but it doesn't seem to compile for the ESP32

Error message: 
"Cannot find source file:
C:/T3-programmable-controller-on-ESP32-master/main/lcd.c "

Thx!

**Comment by dzungpv** [comment]
I have same issue with difference error message. Are you fix it?

**Comment by TemcoLijun** [comment]
I uploaded the latest code, please update and try again.

**Comment by alaarihan-temco** [comment]
I tried to build it after your latest changes but I got this message
```
T3-programmable-controller-on-ESP32/main/ud_str.h:6:10: fatal error: types.h: No such file or directory
 #include "types.h"
```

**Comment by MauriceDuteau** [comment]
Lijun, you should create and auto build project like Alaa has done for the windows application, check with Fandu on this continuous integration method as its called. Also CD, short for continuous deployment, he can help build a script to send the bin file to the update system.
